apiVersion: v1
kind: Service
metadata:
  name: app-kubernetes-service
spec:
  selector:
    app: test-app-kub
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 6000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-kub
spec:
  selector:
    matchLabels:
      app: test-app-kub
  replicas: 5
  template:
    metadata:
      labels:
        app: test-app-kub
    spec:
      containers:
      - name: test-app-kub
        image: app-kub:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 8000